### ISSUE TITLE
vaje.zip

### ISSUE THREAD

**Issue by jaanos** [alikosmac/drzavna_meja#2]
Na repozitoriju imata datoteko `vaje.zip` - iz sporočila ob commitu sklepam, da gre za datoteke vajinega projekta. Seveda bi se spodobilo, da imata te datoteke neposredno na repozitoriju in ne v ZIPu, saj bosta le tako lahko dejansko z njimi delala. Nasploh pa na git ni priporočljivo nalagati binarnih datotek, kot so to ZIP datoteke (sploh, če se bodo spreminjale). Vsebino torej naložita neposredno na repozitorij, samo datoteko ZIP pa pobrišita.

**Comment by matijapretnar** [comment]
Se pridružujem @jaanos, da morata najprej razpakirati to datoteko, preden lahko sploh kaj pokomentirava.

**Comment by jaanos** [comment]
Tole je urejeno, tako da zapiram.
